### ISSUE TITLE
icons

### ISSUE THREAD

**Issue by TheGrumbledook** [juro-privacy/free-privacy-notice#3]
If we are not using the icons due to copyright reasons, would it make some sense to point to specific, individual icons rather than within an SVG file? Even if just an open-source placeholder? Or have the options for either?

**Comment by juro-privacy** [comment]
It's a good thought. You can use the icons if just for your own privacy notice - there's just a limit on streamline icons to distribute further. Would this cover you guys?

Best wishes
Richard


—
Richard Mabey
CEO | juro.com
7-9 Woodbridge Street, London EC1R 0LL

Love using Juro? Leave us a review


Sent from a lawyer -- please excuse long sentences**

--- original message ---
On April 15, 2021, 5:49 PM GMT+1 ***@***.*** wrote:



If we are not using the icons due to copyright reasons, would it make some sense to point to specific, individual icons rather than within an SVG file? Even if just an open-source placeholder? Or have the options for either?

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly, view it on GitHub, or unsubscribe.
--- end of original message ---

**Comment by TheGrumbledook** [comment]
Not really, I'm the brave soul who is looking at how these design patterns could help with Data Processing Agreements too. That would mean a lot of organisation and DPOs using this as a template to include with DPAs. I've copied the project into a different repo rather than fork it (not a dev so keeping it simple) but keen to feed into here about things that would also work in the DPA project. 
All original attributions will be referenced and the project will also be Open Source (already spoken with Stefania)

**Comment by juro-privacy** [comment]
gotcha - thanks for the update!

Best wishes
Richard


—
Richard Mabey
CEO | juro.com
7-9 Woodbridge Street, London EC1R 0LL

Love using Juro? Leave us a review


Sent from a lawyer -- please excuse long sentences**

--- original message ---
On April 19, 2021, 10:54 AM GMT+1 ***@***.*** wrote:



Not really, I'm the brave soul who is looking at how these design patterns could help with Data Processing Agreements too. That would mean a lot of organisation and DPOs using this as a template to include with DPAs. I've copied the project into a different repo rather than fork it (not a dev so keeping it simple) but keen to feed into here about things that would also work in the DPA project.

All original attributions will be referenced and the project will also be Open Source (already spoken with Stefania)

—

You are receiving this because you commented.

Reply to this email directly, view it on GitHub, or unsubscribe.
--- end of original message ---

**Comment by TheGrumbledook** [comment]
Looking at the files, it is going to be hard to unpick this. I might have a chat with a friendly designer and see if we can come up with an Open Source version of the graphics that can be re-used and re-purposed without restrictions. Probably the fairest way to do it for now, but would you consider using something other than the .SVG file? It does make it hard to work with. I am having to comment the code a lot to explain what to move in 'data you give' / 'date we collect'.
Not everyone has the background to make the changes.

**Comment by juro-privacy** [comment]
yes, probably the best way is just to use different graphics.

Best wishes
Richard


—
Richard Mabey
CEO | juro.com
7-9 Woodbridge Street, London EC1R 0LL

Love using Juro? Leave us a review


Sent from a lawyer -- please excuse long sentences**

--- original message ---
On April 23, 2021, 3:13 PM GMT+1 ***@***.*** wrote:



Looking at the files, it is going to be hard to unpick this. I might have a chat with a friendly designer and see if we can come up with an Open Source version of the graphics that can be re-used and re-purposed without restrictions. Probably the fairest way to do it for now, but would you consider using something other than the .SVG file? It does make it hard to work with. I am having to comment the code a lot to explain what to move in 'data you give' / 'date we collect'.

Not everyone has the background to make the changes.

—

You are receiving this because you commented.

Reply to this email directly, view it on GitHub, or unsubscribe.
--- end of original message ---

**Comment by TheGrumbledook** [comment]
Can I ask what was used to create the sprite.svg file? I'm looking at the best option for changing it.

**Comment by TheGrumbledook** [comment]
Can I ask what was used to package together the .svg file?

**Comment by korochinsky** [comment]
Hey, so this privacy-notice at the beginning was the part of another project, which was dynamic and used [gulp-svgstore](https://www.npmjs.com/package/gulp-svgstore) plugin to combine all the icons together in one sprite. And when extracting this privacy-notice as a subproject we just skipped all the dynamic parts to keep the simplicity.
