### ISSUE TITLE
relative links to res folder and others

### ISSUE THREAD

**Issue by TheGrumbledook** [juro-privacy/free-privacy-notice#4]
In demo.html the links back to the res folder are ../ rather than ./ 
This means that the page won't work as it is looking in the wrong place for the files. 
I only just spotted this as I had previously moved files around to a flat structure ...

**Comment by juro-privacy** [comment]
good spot - fix incoming

Best wishes
Richard


—
Richard Mabey
CEO | juro.com
7-9 Woodbridge Street, London EC1R 0LL

Love using Juro? Leave us a review


Sent from a lawyer -- please excuse long sentences**

--- original message ---
On April 23, 2021, 9:20 AM GMT+1 ***@***.*** wrote:



In demo.html the links back to the res folder are ../ rather than ./

This means that the page won't work as it is looking in the wrong place for the files.

I only just spotted this as I had previously moved files around to a flat structure ...

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly, view it on GitHub, or unsubscribe.
--- end of original message ---

**Comment by juro-privacy** [comment]
issue should now be fixed

Best wishes
Richard


—
Richard Mabey
CEO | juro.com
7-9 Woodbridge Street, London EC1R 0LL

Love using Juro? Leave us a review


Sent from a lawyer -- please excuse long sentences**

--- original message ---
On April 23, 2021, 12:05 PM GMT+1 ***@***.*** wrote:


good spot - fix incoming


Best wishes

Richard



—

Richard Mabey

CEO | juro.com

7-9 Woodbridge Street, London EC1R 0LL


Love using Juro? Leave us a review



Sent from a lawyer -- please excuse long sentences**



> On April 23, 2021, 9:20 AM GMT+1 ***@***.*** wrote:



> In demo.html the links back to the res folder are ../ rather than ./

> This means that the page won't work as it is looking in the wrong place for the files.

> I only just spotted this as I had previously moved files around to a flat structure ...

> —

> You are receiving this because you are subscribed to this thread.

> Reply to this email directly, view it on GitHub, or unsubscribe.
--- end of original message ---

**Comment by TheGrumbledook** [comment]
All sorted. Happy to close the issue
